export const YES_NO_OPTIONS = [
    { key: "Yes", value: "yes" },
    { key: "No", value: "no" },
];

/**
 * Legacy attribute keys that may live at the root of a persisted item and must be
 * migrated into the nested `attributes` object when loading initial data.
 */
export const ATTRIBUTE_MIGRATION_KEYS = [
    "gender",
    "colour",
    "size",
    "size_chart",
    "fabric",
    "colour_name",
    "pattern",
    "material",
    "season",
    "occasion",
    "sleeve_length",
    "collar",
    "fit",
    "neck",
    "hemline",
    "coverage",
    "padding",
    "closure_type",
    "fasten_type",
    "water_resistant",
    "sport_type",
    "material_finish",
    "fabric_finish",
    "concern",
    "ingredient",
    "conscious",
    "preference",
    "formulation",
    "skin_type",
    "manufacturer",
    "manufacturer_address",
    "net_quantity",
    "expiry_date",
    "ingredients",
    "model",
    "warranty_period",
    "screen_size",
    "storage",
    "ram",
    "dimensions",
    "weight",
    "dosage_form",
    "prescription_required",
    "composition",
    "side_effects",
    "cuisine",
    "course",
    "allergen_info",
    "serving_size",
    "power_consumption",
    "capacity",
    "energy_rating",
];

/** Default (empty) shape for an item's dynamic attributes bag. */
export const createEmptyAttributes = (): Record<string, string> => ({
    gender: "",
    colour: "",
    size: "",
    size_chart: "",
    fabric: "",
    colour_name: "",
    pattern: "",
    material: "",
    season: "",
    occasion: "",
    sleeve_length: "",
    collar: "",
    fit: "",
    neck: "",
    hemline: "",
    coverage: "",
    padding: "",
    closure_type: "",
    fasten_type: "",
    water_resistant: "",
    sport_type: "",
    material_finish: "",
    fabric_finish: "",
    concern: "",
    ingredient: "",
    conscious: "",
    preference: "",
    formulation: "",
    skin_type: "",
    manufacturer: "",
    manufacturer_address: "",
    net_quantity: "",
    expiry_date: "",
    ingredients: "",
    model: "",
    warranty_period: "",
    screen_size: "",
    storage: "",
    ram: "",
    dimensions: "",
    weight: "",
    dosage_form: "",
    prescription_required: "",
    composition: "",
    side_effects: "",
    cuisine: "",
    course: "",
    allergen_info: "",
    serving_size: "",
    power_consumption: "",
    capacity: "",
    energy_rating: "",
});
