import {
    BACKPACK_STYLE,
    BASE_METAL,
    BOTTOM_TYPE,
    BUCKLE_MATERIAL,
    BUCKLE_TYPE,
    CLOSURE_TYPE,
    COLLAR,
    COVERAGE,
    DIAL_SHAPE,
    DISPLAY,
    FABRIC,
    FABRIC_FINISH,
    FACE_SHAPE,
    FASTEN_TYPE,
    FEATURES,
    FIT,
    FOOTWEAR_TYPE,
    FRAME_MATERIAL,
    FRAME_SHAPE,
    FRAME_SIZE,
    FRAME_STYLE,
    FRAME_TYPE,
    FRONT_STYLING,
    GEM_TYPE,
    GENDER,
    HEMLINE,
    INSOLE,
    LENS_MATERIAL,
    LOCK_TYPE,
    MATERIAL,
    MATERIAL_FINISH,
    MIDSOLE,
    NECK,
    OCCASION,
    ORNAMENTATION,
    OUTSOLE,
    PADDING,
    PATTERN,
    PLATING,
    POWER_TYPE,
    SEAM,
    SEASON,
    SIZE,
    SLEEVE_LENGTH,
    SOCKS_LENGTH,
    SOLE_MATERIAL,
    SPORT_TYPE,
    STONE_TYPE,
    STRAP_MATERIAL,
    SWEATSHIRT_TYPE,
    TOE_SHAPE,
    TOP_TYPE,
    TREND,
    WAIST_BAND,
    WAIST_RISE,
    WASH_TYPE,
} from "./fashionEnums";

type FashionEntry = {
    [key: string]: {
        mandatory: boolean;
        value: unknown;
    };
};

const BASE_FASHION_FIELDS: FashionEntry = {
    gender: { mandatory: false, value: GENDER },
    colour: { mandatory: false, value: "/^#([a-fA-F0-9]{6})/" },
    size: { mandatory: false, value: SIZE },
    brand: { mandatory: false, value: [] },
    size_chart: { mandatory: false, value: "/^https?://[-A-Za-z0-9+&@#/%?=~_|!:,.;]*[-A-Za-z0-9+&@#/%=~_|]$/" },
    fabric: { mandatory: false, value: FABRIC },
    strap_material: { mandatory: false, value: STRAP_MATERIAL },
    water_resistant: { mandatory: false, value: [] },
    display: { mandatory: false, value: DISPLAY },
    glass_material: { mandatory: false, value: [] },
    colour_name: { mandatory: false, value: "/^[a-z ]+$/" },
    sport_type: { mandatory: false, value: SPORT_TYPE },
    base_metal: { mandatory: false, value: BASE_METAL },
    plating: { mandatory: false, value: PLATING },
    care_instructions: { mandatory: false, value: [] },
    wash_type: { mandatory: false, value: WASH_TYPE },
    weight: { mandatory: false, value: [] },
    length: { mandatory: false, value: [] },
    breadth: { mandatory: false, value: [] },
    height: { mandatory: false, value: [] },
    features: { mandatory: false, value: FEATURES },
    fabric_finish: { mandatory: false, value: FABRIC_FINISH },
    material: { mandatory: false, value: MATERIAL },
    material_finish: { mandatory: false, value: MATERIAL_FINISH },
    pattern: { mandatory: false, value: PATTERN },
    occasion: { mandatory: false, value: OCCASION },
    season: { mandatory: false, value: SEASON },
    trend: { mandatory: false, value: TREND },
    fit: { mandatory: false, value: FIT },
    collar: { mandatory: false, value: COLLAR },
    neck: { mandatory: false, value: NECK },
    bundles: { mandatory: false, value: [] },
    max_sale_quantity: { mandatory: false, value: [] },
    hemline: { mandatory: false, value: HEMLINE },
    lining: { mandatory: false, value: [] },
    num_pockets: { mandatory: false, value: [] },
    reversible: { mandatory: false, value: [] },
    bottom_type: { mandatory: false, value: BOTTOM_TYPE },
    top_type: { mandatory: false, value: TOP_TYPE },
    front_styling: { mandatory: false, value: FRONT_STYLING },
    sleeve_length: { mandatory: false, value: SLEEVE_LENGTH },
    sweatshirt_type: { mandatory: false, value: SWEATSHIRT_TYPE },
    fragile: { mandatory: false, value: [] },
    liquid: { mandatory: false, value: [] },
    hazardous: { mandatory: false, value: [] },
    power_type: { mandatory: false, value: POWER_TYPE },
    battery_life: { mandatory: false, value: [] },
    bluetooth: { mandatory: false, value: [] },
    call_function: { mandatory: false, value: [] },
    heart_rate_monitor: { mandatory: false, value: [] },
    pedometer: { mandatory: false, value: [] },
    sleep_monitor: { mandatory: false, value: [] },
    spo2_monitor: { mandatory: false, value: [] },
    warranty: { mandatory: false, value: [] },
    buckle_material: { mandatory: false, value: BUCKLE_MATERIAL },
    buckle_type: { mandatory: false, value: BUCKLE_TYPE },
    waist_rise: { mandatory: false, value: WAIST_RISE },
    socks_length: { mandatory: false, value: SOCKS_LENGTH },
    footwear_type: { mandatory: false, value: FOOTWEAR_TYPE },
    insole: { mandatory: false, value: INSOLE },
    sole_material: { mandatory: false, value: SOLE_MATERIAL },
    toe_shape: { mandatory: false, value: TOE_SHAPE },
    outsole: { mandatory: false, value: OUTSOLE },
    fasten_type: { mandatory: false, value: FASTEN_TYPE },
    midsole: { mandatory: false, value: MIDSOLE },
    backpack_style: { mandatory: false, value: BACKPACK_STYLE },
    closure_type: { mandatory: false, value: CLOSURE_TYPE },
    stone_type: { mandatory: false, value: STONE_TYPE },
    gem_type: { mandatory: false, value: GEM_TYPE },
    dial_shape: { mandatory: false, value: DIAL_SHAPE },
    frame_type: { mandatory: false, value: FRAME_TYPE },
    frame_shape: { mandatory: false, value: FRAME_SHAPE },
    frame_colour: { mandatory: false, value: [] },
    frame_size: { mandatory: false, value: FRAME_SIZE },
    frame_material: { mandatory: false, value: FRAME_MATERIAL },
    frame_style: { mandatory: false, value: FRAME_STYLE },
    face_shape: { mandatory: false, value: FACE_SHAPE },
    lens_material: { mandatory: false, value: LENS_MATERIAL },
    lens_colour: { mandatory: false, value: [] },
    laptop_compartment: { mandatory: false, value: [] },
    strap_type: { mandatory: false, value: [] },
    volume: { mandatory: false, value: [] },
    lock_type: { mandatory: false, value: LOCK_TYPE },
    ornamentation: { mandatory: false, value: ORNAMENTATION },
    coverage: { mandatory: false, value: COVERAGE },
    padding: { mandatory: false, value: PADDING },
    seam: { mandatory: false, value: SEAM },
    waist_band: { mandatory: false, value: WAIST_BAND },
    sustainability: { mandatory: false, value: [] },
    handcrafted: { mandatory: false, value: [] },
    craftmark: { mandatory: false, value: [] },
};

function createEntry(mandatoryFields: string[], excludeFields: string[] = []): FashionEntry {
    const entry: FashionEntry = {};
    for (const [key, def] of Object.entries(BASE_FASHION_FIELDS)) {
        if (excludeFields.includes(key)) continue;
        entry[key] = {
            mandatory: mandatoryFields.includes(key),
            value: def.value,
        };
    }
    return entry;
}

export const fashion: Record<string, FashionEntry> = {
    Shirts: createEntry(["gender", "colour", "size", "brand", "size_chart", "fabric", "colour_name"]),
    "T Shirts": createEntry(["gender", "colour", "size", "brand", "size_chart", "fabric", "colour_name"]),
    Sweatshirts: createEntry(["gender", "colour", "size", "brand", "size_chart", "fabric", "colour_name"]),
    "Kurtas & Kurta Sets": createEntry(["gender", "colour", "size", "brand", "size_chart", "fabric", "colour_name"]),
    "Jackets & Coats": createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    Sweaters: createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    "Stoles and Scarves": createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    Mufflers: createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    Suits: createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    Sherwanis: createEntry(["gender", "colour", "size", "brand", "size_chart", "fabric", "colour_name"]),
    "Track Shirts": createEntry(["gender", "colour", "size", "brand", "size_chart", "fabric", "colour_name"]),
    "Track Suits": createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    "Unstitched Fabrics": createEntry(["gender", "colour", "brand", "fabric", "colour_name"], ["size"]),
    Dresses: createEntry(["gender", "colour", "size", "brand", "size_chart", "fabric", "colour_name"]),
    Tops: createEntry(["gender", "colour", "size", "brand", "size_chart", "fabric", "colour_name"]),
    Trousers: createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    Capris: createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    Coordinates: createEntry(["gender", "colour", "size", "brand", "size_chart", "fabric", "colour_name"]),
    Playsuits: createEntry(["gender", "colour", "size", "brand", "size_chart", "fabric", "colour_name"]),
    Jumpsuits: createEntry(["gender", "colour", "size", "brand", "size_chart", "fabric", "colour_name"]),
    "Shrugs & Blouses": createEntry(["gender", "colour", "size", "brand", "size_chart", "fabric", "colour_name"]),
    "Blazers & Waistcoats": createEntry(["gender", "colour", "size", "brand", "size_chart", "fabric", "colour_name"]),
    "Tights, Leggings & Jeggings": createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    "Track Pants": createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    Jeans: createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    Shorts: createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    Joggers: createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    "Dhotis & Dhoti Pants": createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    Churidars: createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    Salwars: createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    "Dungarees & Jumpsuits": createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    Skirts: createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    "Clothing Sets": createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    Belts: createEntry(["gender", "colour", "brand", "size_chart", "colour_name", "material", "reversible"], ["size"]),
    "Caps & Hats": createEntry(["gender", "colour", "brand", "colour_name", "material"], ["size"]),
    "Kurtis, Tunics": createEntry(["gender", "colour", "size", "brand", "size_chart", "fabric", "colour_name"]),
    Sarees: createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    "Ethnic Wear": createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    Palazzos: createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    "Dress Materials": createEntry(["gender", "colour", "size", "brand", "size_chart", "fabric", "colour_name"]),
    "Lehenga Cholis": createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    "Dupattas & Shawls": createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    "Burqas & Hijabs": createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    Blouses: createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    "Blouse Pieces": createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    Briefs: createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    Boxers: createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    Vests: createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    Robes: createEntry(["gender", "colour", "size", "brand", "size_chart", "fabric", "colour_name"]),
    "Night Suits": createEntry(["gender", "colour", "size", "brand", "size_chart", "fabric", "colour_name"]),
    "Thermal Wear": createEntry(["gender", "colour", "size", "brand", "size_chart", "fabric", "colour_name"]),
    "Swim Bottoms": createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    Swimwear: createEntry(["gender", "colour", "size", "brand", "size_chart", "fabric", "colour_name"]),
    Bra: createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    Shapewear: createEntry(["gender", "colour", "size", "brand", "size_chart", "fabric", "colour_name"]),
    "Sleepwear & Loungewear": createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    Camisoles: createEntry(["gender", "colour", "size", "brand", "size_chart", "fabric", "colour_name"]),
    "Lingerie Sets & Accessories": createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    "Bath Robes": createEntry(["gender", "colour", "size", "brand", "size_chart", "fabric", "colour_name"]),
    Towels: createEntry(["gender", "colour", "size", "brand", "colour_name"]),
    Pyjamas: createEntry(["gender", "colour", "size", "brand", "size_chart", "fabric", "colour_name"]),
    "Party Wear": createEntry(["gender", "colour", "size", "brand", "size_chart", "fabric", "colour_name"]),
    "Innerwear & Sleepwear": createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    "Nightwear & Loungewear": createEntry(["gender", "colour", "size", "brand", "size_chart", "fabric", "colour_name"]),
    Watches: createEntry(["gender", "colour", "brand", "strap_material", "water_resistant", "display", "glass_material", "colour_name"], ["size"]),
    Gloves: createEntry(["gender", "colour", "brand", "colour_name"], ["size"]),
    Socks: createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    Stockings: createEntry(["gender", "colour", "brand", "fabric", "colour_name"], ["size"]),
    Laces: createEntry(["gender", "colour", "fabric", "colour_name"], ["brand", "size"]),
    "Soles & Charms": createEntry(["gender", "colour", "brand", "colour_name"], ["size"]),
    "Shoe Racks & Organisers": createEntry(["gender", "colour", "size", "brand", "colour_name"]),
    "Shoe Care - Accessories": createEntry(["gender", "colour", "size", "brand", "colour_name"]),
    "Flip-Flops & Flats": createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    "Sandals & Floaters": createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    Backpacks: createEntry(["gender", "colour", "size", "brand", "fabric", "colour_name"]),
    Handbags: createEntry(["gender", "colour", "brand", "colour_name"], ["size"]),
    "Trolley, Luggage & Suitcases": createEntry(["gender", "colour", "size", "brand", "fabric", "colour_name"]),
    "Formal Shoes": createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    "Casual Shoes": createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    "Sports Shoes": createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name", "sport_type"], ["size"]),
    "Outdoor Shoes": createEntry(["gender", "colour", "brand", "size_chart", "colour_name"], ["size"]),
    "Work & Safety Shoes": createEntry(["gender", "colour", "brand", "size_chart", "colour_name"], ["size"]),
    "Ethnic Shoes": createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    Boots: createEntry(["gender", "colour", "brand", "size_chart", "colour_name"], ["size"]),
    Heels: createEntry(["gender", "colour", "brand", "size_chart", "fabric", "colour_name"], ["size"]),
    "Contact Lenses": createEntry(["gender", "colour", "brand", "colour_name"], ["size"]),
    "Eye Glasses": createEntry(["gender", "colour", "brand", "colour_name"], ["size"]),
    "Eye Glass Frames": createEntry(["gender", "colour", "brand", "colour_name"], ["size"]),
    Sunglasses: createEntry(["gender", "colour", "brand", "colour_name"], ["size"]),
    "Contact Lens Cases": createEntry(["gender", "colour", "brand", "colour_name"], ["size"]),
    "Contact Lens Solutions": createEntry(["gender", "colour", "size", "brand", "colour_name"]),
    "Contact Lens Tweezers": createEntry(["gender", "colour", "size", "brand", "colour_name"]),
    "Eyeglasses Pouches & Cases": createEntry(["gender", "colour", "brand", "colour_name"], ["size"]),
    "Microfiber Wipes": createEntry(["gender", "colour", "size", "brand", "colour_name"]),
    "Eyewear Slings": createEntry(["gender", "colour", "size", "brand", "colour_name"]),
    Bracelets: createEntry(["gender", "colour", "brand", "colour_name", "base_metal", "plating"], ["size"]),
    Chains: createEntry(["gender", "colour", "brand", "colour_name", "base_metal", "plating"], ["size"]),
    Mangalsutra: createEntry(["gender", "colour", "brand", "colour_name", "base_metal", "plating"], ["size"]),
    Anklets: createEntry(["gender", "colour", "brand", "colour_name", "base_metal", "plating"], ["size"]),
    "Bangles & Bracelets": createEntry(["gender", "colour", "brand", "colour_name"], ["size"]),
    Necklaces: createEntry(["gender", "colour", "brand", "colour_name", "base_metal", "plating"], ["size"]),
    Earrings: createEntry(["gender", "colour", "brand", "colour_name", "base_metal", "plating"], ["size"]),
    "Jewellery Sets": createEntry(["gender", "colour", "brand", "colour_name", "base_metal", "plating"], ["size"]),
    "Nosepins & Noserings": createEntry(["gender", "colour", "brand", "colour_name", "base_metal", "plating"], ["size"]),
    Pendants: createEntry(["gender", "colour", "brand", "colour_name", "base_metal", "plating"], ["size"]),
    Rings: createEntry(["gender", "colour", "brand", "colour_name", "base_metal", "plating"], ["size"]),
    "Toe Rings": createEntry(["gender", "colour", "brand", "colour_name", "base_metal", "plating"], ["size"]),
    "Gold Coins": createEntry(["gender", "colour", "brand", "colour_name", "base_metal", "plating"], ["size"]),
    Brooch: createEntry(["gender", "colour", "brand", "colour_name", "base_metal", "plating"], ["size"]),
};
